### ISSUE TITLE
How to generate the keyword_dict? 

### ISSUE THREAD

**Issue by iskindar** [swtv-kaist/ZigZagFuzz#1]
Thank you for open-sourcing the interesting project ZigzagFuzz. 
I noticed that the paper mentioned a Python script for extracting program options, but I was unable to locate it in the repository. Could you provide guidance on where to find it or share the script if it is not included in the current version?

**Comment by ahcheongL** [comment]
Hi, we used different Python scripts for different programs since the programs have different usage message structures.
Since those usage messages are relatively short, I believe you can make your own script to gather keywords from them.
For reference, you can get example dictionary files in `paper_exp/keyword_dict` in the `tosem_2024` branch.

**Comment by iskindar** [comment]
Thanks for your reply! I’ll refer to the example dictionary format in the tosem_2024 branch and write a script to extract options accordingly.
